### ISSUE TITLE
Docker compose configuration file missing

### ISSUE THREAD

**Issue by algocashier** [devfinwiz/Fin-Maestro#55]
Unable to use docker compose to build app, the configuration file seems to be missing .yml file is not in any directory

**Comment by devfinwiz** [comment]
Hi @algocashier ,
The doxker deployment mode is only available for branch 'docker' and the same isn't integrated for the master branch.

Try switching branch first and you'll find the compose file there. 

Note: I do not actively maintain this repository anymore due to my busy schedule, apologies for the inconvenience.

**Comment by devfinwiz** [comment]
Assuming the query has been answered, I'll close this issue now. Kindly reopen if you think otherwise.
